=begin
#AKEYLESS Vault API

#RESTFull API for interacting with AKEYLESS Vault API

OpenAPI spec version: 0.1.1
Contact: refael@akeyless.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

module SwaggerClient
  VERSION = '1.0.0'
end
