=begin
#AKEYLESS Vault API

#RESTFull API for interacting with AKEYLESS Vault API

OpenAPI spec version: 0.1.1
Contact: refael@akeyless.io
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ReplyObj
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ReplyObj' do
  before do
    # run before each test
    @instance = SwaggerClient::ReplyObj.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ReplyObj' do
    it 'should create an instance of ReplyObj' do
      expect(@instance).to be_instance_of(SwaggerClient::ReplyObj)
    end
  end
  describe 'test attribute "command"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "response"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "status"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "token"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
